[package]
name = "pywr-schema"
version = "0.1.0"
edition = "2021"

[lib]
name = "pywr_schema"
path = "src/lib.rs"


[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
time = { version = "0.3.14", features = ["serde", "serde-well-known", "serde-human-readable"] }
